# =============================================
#   Application Config
# =============================================
spring.application.name=product-catalog

# =============================================
#   H2 In-Memory Database
#   No MySQL setup needed!
#   Visit http://localhost:8080/h2-console to view data
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecart
spring.datasource.username=root
spring.datasource.password=abcd@1234

